"use client"

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import MyProvider from "@/lib/Provider";

// import Swiper and modules styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "react-toastify/dist/ReactToastify.css";
import "react-quill/dist/quill.snow.css";
import { Provider } from "react-redux";
import { store } from "@/redux/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Trip4all",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <MyProvider>
    <Provider store={store}>
      <html lang="en">
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <body className={`${inter.className} bg-gray-100`}>
          {children}
          <ToastContainer />
        </body>
      </html>
    </Provider>
    // </MyProvider>
  );
}
